name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: "Agg"   # evita errores de display en matplotlib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (project + dev)
        run: python -m pip install -e ".[dev]"

      - name: Ruff
        run: python -m ruff check .

      - name: Black
        run: python -m black --check .

      - name: Mypy
        run: python -m mypy .

      - name: Pytest
        run: python -m pytest -q